### ISSUE TITLE
Falta de Tradução no Componente "ContactForm.tx"

### ISSUE THREAD

**Issue by Brunin12** [gabinfinity/gabriel-portfolio#1]
Olá, Gabriel! 

Curti muito este seu portifólio e gostaria de ajudar a melhorar ele! enquanto aprendia e mechia em algumas coisas percebi que na parte do contato você não havia traduzindo a mensagem de retorno (erro bobo), deste trecho:

`const { status, handleFormSubmit } = useContactForm();

    if (status) {
        return (
            <FormStatus> 
                <h1>Formulário de contato enviado com sucesso!</h1>
                <h6>Entrarei em contato em breve. Obrigado.</h6>
            </FormStatus>
        );
    }`

[ContactForm.zip](https://github.com/gabinfinity/gabriel-portfolio/files/13698285/ContactForm.zip)

**Comment by gabinfinity** [comment]
Olá, Bruno. Muito obrigado, acabou passando desapercebido kk. Irei arrumar aqui, e novamente, Obrigado.
